### ISSUE TITLE
Passing style props to Animated.View throws warning

### ISSUE THREAD

**Issue by thomasbruketta** [constelation/monorepo#11]
When creating an Animated view like so:
```
const AnimatedView = Animated.createAnimatedComponent(View);
...
<AnimatedView
    position='absolute'
    overflow='hidden'
    top={80}
>
```
The following warnings are thrown:
https://cl.ly/3T111D02070d
<img width="904" alt="screen shot 2016-11-16 at 10 22 58 pm" src="https://cloud.githubusercontent.com/assets/5964541/20378483/4c67619c-ac4b-11e6-94e6-d940dc4e19f9.png">

**Comment by thomasbruketta** [comment]
Not a huge issue since its just a warning but it seriously clutters up the console. Maybe we just find a way to suppress the warning.

**Comment by kylpo** [comment]
Think we discovered this is only when using React Native's View, not Constelation's. Closing...
