### ISSUE TITLE
<Style_> does not pass props correctly to <Animated.View>

### ISSUE THREAD

**Issue by thomasbruketta** [constelation/monorepo#14]
This is a fairly major blocker to using the <Style_> component in RN. It throws a prop error when attempting to pass props to <View> and seems to conflict with the Animated styles. It may be due to the way in which Animated wraps the <View> component.

**Comment by mikehobi** [comment]
Could you post the specific prop error? Is it only when animated values are included in `<Style_>`? or any style?

**Comment by mikehobi** [comment]
Also does this work?

```
<Style_
    style={{
        backgroundColor: 'blue',
    }}
>
    <Animated.View />
</Style_>

**Comment by mikehobi** [comment]
Closing issue. working ex:

```
import View from 'constelation-View'
const AnimatedView = Animated.createAnimatedComponent(View)
```

```
<Style_
  backgroundColor={this.myAnimatedColor}
  transform={[
    {translateY: this.myAnimatedTranslate},
  ]}
 >
  <AnimatedView
    width={100}
    height={this.myAnimatedValue}
/>
</Style_>
```
