### ISSUE TITLE
flow syntax coloring

### ISSUE THREAD

**Issue by mosesoak** [constelation/monorepo#29]
@kylpo this is low pri, but just to call it to your attention: 

using VS Code with the official flowtype plugin, files marked .js.flow don't syntax-color. When changing it to .flow.js they do. 

Is .flow a standard that others use? If so we could report this issue to flowtype for their VS Code plugin.

**Comment by kylpo** [comment]
It is standard. See https://flowtype.org/docs/declarations.html#declaration-files

**Comment by mosesoak** [comment]
I got a VS Code workaround for this and Fastfile (which doesn't have a .rb extension)

```json
  "files.associations": {
    "**/Fastfile": "ruby",
    "*.flow": "javascript"
  }
```
