### ISSUE TITLE
<Image> component requires a height to be set

### ISSUE THREAD

**Issue by thomasbruketta** [constelation/monorepo#30]
RN's implementation of image was intended to allow and image to be rendered to its original dimension with nothing but the source given.

ex:
```
<Image source="http://placehold.it/350x150">
```
The above yields a 350x150 image with RN's Image component but nothing with constelations `Image` component.

**Comment by kylpo** [comment]
Woah, found the problem. Passing in `height: undefined, width: undefined` messes up RN's Image. Looks like I might have a RN pull request in my sights...

**Comment by kylpo** [comment]
Should be fixed with https://github.com/constelation/monorepo/commit/e4f48d65a88bce064bbdb91d5d2e25303c1dba93. Learned a LOT from this one!

Closing. Please re-open if you still see this after updating.
