### ISSUE TITLE
Animate_ native

### ISSUE THREAD

**Issue by kylpo** [constelation/monorepo#32]
Consider `transition` prop like https://github.com/oblador/react-native-animatable#generic-transitions. This'd mean Style, View, etc would need to handle transitions separately.

- [x] Handle transforms
- [x] `<AnimationConfig durationModifier={2}>` wrapper to slow down all animations in app in dev mode
- [x] Handle animation direction
- [x] Handle Spring. Could use it if no duration/delay are set?
- [x] Research ref-less trigger (thinking about Netflix here). What if trigger was a mobx observable?
- [x] Implement keyframes template literal
- [x] Adapt interpolations and events when props change
- [ ] Prevent `repeat` with `triggerEvent` - got me in to trouble

Current API plan (see notes below of other options):
Start with inline object literals.
```jsx
<Animate_
  autoplay
  ref='box1'
  duration={400}
  delay={200}
  easing='inOut'
  animation={{
    0: {
      opacity: 0.5,
    },
    0.5: {
      opacity: 0,
      left: 20,
    },
    1: {
      opacity: 1,
      left: 0,
    },
  }}
  onStart={this.onStart}
  onEnd={this.onEnd}
>
  <Image source={require('images/logo.png')} />
</Animate_>
```

or this condensed version if it helps readability

```jsx
<Animate_
  autoplay
  ref='box1'
  duration={400}
  delay={200}
  easing='inOut'
  animation={{
    0: {opacity: 0.5},
    0.5: {opacity: 0, left: 20},
    1: {opacity: 1, left: 0},
  }}
  onStart={this.onStart}
  onEnd={this.onEnd}
>
  <Image source={require('images/logo.png')} />
</Animate_>
```

Pros
- copy/paste-able!
- clearly see which attributes are animated in the render

Cons
- object literal is created on every `render()`

After the API has been thoroughly vetted, switch to tagged template literal (`keyframes`), which converts the keyframe into a valid json string. `Animate_` will take that string and use `JSON.Parse()` to hydrate it to an object for use. The benefit here is re-enabling `Animate_` as a `PureComponent` with immutable props again.

```jsx
<Animate_
  autoplay
  ref='box1'
  duration={400}
  delay={200}
  easing='inOut'
  animation={keyframes`
    0: {
      opacity: 0.5,
    },
    0.5: {
      opacity: 0,
      left: 20,
    },
    1: {
      opacity: 1,
      left: 0,
    },
  `}
  onStart={this.onStart}
  onEnd={this.onEnd}
>
  <Image source={require('images/logo.png')} />
</Animate_>
```

Bonus points: editor extension to color-code within the tagged template literal like `styled-components` does.

**Comment by mosesoak** [comment]
What about just using Animatable inside Animate_, at least on the native side? Avoids re-implementing, can still be choosy about what portions of the the API to expose, can ditch later as needed...

(Not sure about how Animate_ will be implemented on the web side...)

**Comment by kylpo** [comment]
Notes from tinkering with inline animation values:
```jsx
            <Animate_
              ref='box1'
              autoplay={false}
              duration={1000}
              delay={200}
              easing='inOut'
              onStart={() => {console.log('onStart')}}
              onEnd={() => {console.log('onEnd')}}

              fromOpacity={0}
              toOpacity={1}

              opacity='0 1'
              height='20 200'
              width='20 200'

              opacity={animated(0, 1)}
              width={animated(20, 200)}
            >
              <Style_
                backgroundColor='purple'
                opacity={animated(0,1)}
                // opacity={[0, 1]}
              >
                <View
                  height={200}
                  width={animated(20, 200)}
                />
              </Style_>
            </Animate_>
```

**Comment by kylpo** [comment]
Maybe Tagged template literals could work? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

Also check out https://github.com/declandewet/common-tags

```jsx
        <Animate_
          animation={keyframes`
            0: {
              opacity: 0.5,
            },
            0.5: {
              opacity: 0,
              left: 20,
            },
            1: {
              opacity: 1,
              left: 0,
            }
          `}
          easing={Easing.sin}
          duration={400}
        >
          <Image source={require('images/logo.png')} />
        </Animate_>

```

**Comment by kylpo** [comment]
Using child function:

```jsx
<Animate_
  ref='box1'
  duration={1000}
  delay={200}
  easing='inOut'
  animation={box1Keyframes}
  onStart={this.onStart}
  onEnd={this.onEnd}
>
  {(animated, passProps) =>
      <Style_
        backgroundColor='purple'
        opacity={animated.opacity}
      >
        <View
          {...passProps}
          width={animated.width}
          height={animated.height}
        />
      </Style_>
  }
</Animate_>

```

or even a step further:
```js
const box1Animation = {
  autoplay: false,
  duration: 1000,
  delay: 200,
  easing: 'inOut',
  onStart: () => {console.log('onStart')},
  onEnd: () => {console.log('onEnd')},
  animation: {
    from: {
      opacity: 0.2,
      width: 20,
      height: 20,
    },
    to: {
      opacity: 1,
      width: 200,
      height: 200,
    },
  },
}

...

<Animate_ animation={box1Animation}>
  {(animated, passProps) =>
      <Style_
        backgroundColor='purple'
        opacity={animated.opacity}
      >
        <View
          {...passProps}
          width={animated.width}
          height={animated.height}
        />
      </Style_>
  }
</Animate_>

```

or spread the props for this different style like:

```jsx
<Animate_ { ...box1Animation }>
  {(animated, passProps) =>
      <Style_
        backgroundColor='purple'
        opacity={animated.opacity}
      >
        <View
          {...passProps}
          width={animated.width}
          height={animated.height}
        />
      </Style_>
  }
</Animate_>
```

Pros: 
- I like that this shows which props are animated within the `Animate_`. This method also prevents the dev from override something that was intended to be an animated value.

Cons:
- kind of a bummer to need the second arg of `passProps` to the child function (to pass props from wrappers like `Event_` and set `animated=true`.
- more visual weight and complexity using child function
- breaks the copy/paste-ability. Can't just take the jsx and run with it. I'd need to take the corresponding animation object.
  - even worse, when I change that animation object, I'll need to reflect the change in the child components. For example, if I remove `opacity` from the animation, I delete it from the animation object, then delete it from the child `Style_`
