### ISSUE TITLE
View components or components wrapped with Event_ return AnimatedComponent

### ISSUE THREAD

**Issue by mikehobi** [constelation/monorepo#34]
Issue: View components that are wrapped w/ `Event_` or have the `animated` prop set to true. Will return an `AnimatedComponent` when calling for a `refNode`

Example:
```
<View
    refNode={this.setRef}
    animated
/>
```

```
<Event_
    onPress={this.handleOnPress}
    pressEffect='opacity'
    activeOpacity={0.6}
>
    <View
        refNode={this.setRef}
    />
</Event_>
```

```
setRef = (node) => {
    // node is an AnimatedComponent
}
```

This makes us unable to call functions such as `measure`, `blur`, `focus` ect...

Possible solution, check if `AnimatedComponent` return `node._component` instead.

**Comment by kylpo** [comment]
Closed in https://github.com/constelation/monorepo/commit/80adc8daa43a3631bda3202a0bccf0dd34a9ab1f
