### ISSUE TITLE
Event_.native layout errors

### ISSUE THREAD

**Issue by mosesoak** [constelation/monorepo#39]
simple button defined like this, with no other views surrounding it in the component,

```javascript
          <Event_
            hitSlop
            onPress={this.handleClosePress}
            pressEffect='opacity'
          >
            <View
              position='absolute'
              top={44}
              left={24}
            >
              <Image
                source={require('images/icons/close-white.png')}
              />
            </View>
          </Event_>

```

throws 3 times in a single render:

![screen shot 2017-02-01 at 4 33 20 pm](https://cloud.githubusercontent.com/assets/24345/22532486/32790064-e89c-11e6-852d-c5c167c01647.png)

Removing the 'top' prop from the enclosed View doesn't change the error.

**Comment by kylpo** [comment]
I think this is from `hitSlop` being declared as a boolean in `Event_`. It should be a number or object.

Closing. Please re-open if `hitSlop` was not the problem.
