### ISSUE TITLE
Passing a Boolean as a property to `constelation-view` throws a prop warning.

### ISSUE THREAD

**Issue by mikehobi** [constelation/monorepo#68]
`Failed prop type: Invalid prop 'borderColor' supplied to 'View': false`
and
`Failed prop type: Invalid prop 'borderColor' supplied to 'RCTView': false`

We would need to run a check on what style props we pass down? Might be a non-issue.

**Comment by kylpo** [comment]
Yeah, looks like this is a valid warning for now. Maybe RN will handle `false` values like the web does in the future?
