### ISSUE TITLE
Margins not recognized within ternary when using Event vs View

### ISSUE THREAD

**Issue by heaversm** [constelation/monorepo#70]
When swapping out a constelation view for a constelation `Event` component, margins are disregarded, both as style props `style={{marginLeft: ... }}` and as direct props `marginLeft={...}` 
as seen in screenshots below:

![screen shot 2017-04-11 at 11 18 38 am](https://cloud.githubusercontent.com/assets/520541/24924431/9a74b6ca-1ea9-11e7-84ae-a3f418041181.png)
![screen shot 2017-04-11 at 11 17 43 am](https://cloud.githubusercontent.com/assets/520541/24924430/9a73a4b0-1ea9-11e7-9d1b-7dcfc69eb11b.png)

**Comment by kylpo** [comment]
Hey @heaversm, this one is actually working as intended. `Event` is a shortcut for wrapping a dummy `View` (no props). If you need a `View` with props, it should be explicitly defined by refactoring `<Event>` => `<Event_>` `<View>`
